import { Command, CommanderError, Option } from "commander";
import { readFileSync } from "node:fs";
import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import {
  checkGhCli,
  fetchRepoRuns,
  fetchMultiRepoRuns,
  fetchPrRuns,
  fetchPrTimings,
  LARGE_ORG_THRESHOLD,
} from "./github.js";
import type { FetchResult } from "./github.js";
import { resolveRepos, formatResolveLog } from "./resolve.js";
import { aggregate, groupByActor } from "./aggregate.js";
import { aggregatePrCost } from "./billing.js";
import { renderTable, renderCsv, renderJson, renderMarkdown, renderPrCostMarkdown, renderPrCostJson, formatRepoDisplay, formatFetchSummary } from "./output.js";
import type { CliOptions, SortField, GroupBy } from "./types.js";
import { EXIT_SUCCESS, EXIT_ERROR, EXIT_NO_DATA } from "./types.js";
import { todayStr, startOfMonthStr, parseDate, validateDateRange } from "./dates.js";
import { causeChain } from "./errors.js";

const pkg = JSON.parse(
  readFileSync(resolve(__dirname, "..", "package.json"), "utf-8"),
) as { version: string };

/** Shape returned by Commander .opts() — mirrors the option definitions below. */
interface RawOpts {
  readonly repo?: readonly string[];
  readonly org?: string;
  readonly exclude?: readonly string[];
  readonly groupBy?: GroupBy;
  readonly pr?: number;
  readonly since?: string;
  readonly until?: string;
  readonly format: "table" | "csv" | "json" | "markdown";
  readonly sort: SortField;
  readonly includeForks?: boolean;
  readonly includeArchived?: boolean;
  readonly csv?: string;
  readonly markdownFile?: string;
}

async function fetchRuns(
  repos: readonly string[],
  since: string,
  until: string,
): Promise<readonly FetchResult[]> {
  process.stderr.write(
    `Fetching GitHub Actions runs for ${formatRepoDisplay(repos)} (${since} to ${until})...\n`,
  );

  if (repos.length > LARGE_ORG_THRESHOLD) {
    process.stderr.write(
      `  Warning: scanning ${repos.length} repos — this may take a while and could hit API rate limits\n`,
    );
  }

  const results =
    repos.length === 1
      ? [await fetchRepoRuns(repos[0], since, until)]
      : await fetchMultiRepoRuns(repos, since, until);

  const summary = formatFetchSummary(results);
  if (summary) process.stderr.write(summary + "\n");

  return results;
}

async function runPrCost(options: CliOptions): Promise<number> {
  const pr = options.pr!;
  if (options.repos.length !== 1) {
    throw new Error("--pr requires exactly one repository (use --repo owner/repo)");
  }
  const repo = options.repos[0];

  process.stderr.write(`Fetching CI runs for ${repo} PR #${pr}...\n`);
  const prRuns = await fetchPrRuns(repo, pr);

  if (prRuns.length === 0) {
    process.stderr.write(`No completed workflow runs found for PR #${pr}.\n`);
    return EXIT_NO_DATA;
  }

  process.stderr.write(`Found ${prRuns.length} run${prRuns.length !== 1 ? "s" : ""}, fetching billing data...\n`);
  const { timings, warnings, estimated } = await fetchPrTimings(repo, prRuns);

  if (estimated) {
    process.stderr.write(`  Billable minutes are 0 — fetched job durations for ${timings.length} run${timings.length !== 1 ? "s" : ""} as fallback\n`);
  }

  for (const warning of warnings) {
    process.stderr.write(`  Warning: ${warning}\n`);
  }

  if (timings.length === 0) {
    const detail = estimated
      ? "Billing API returned 0 minutes and job duration fallback also failed."
      : "Could not fetch billing data for any run.";
    process.stderr.write(`${detail}\n`);
    return EXIT_NO_DATA;
  }

  const costSummary = aggregatePrCost(timings, pr, repo, estimated);
  const markdown = renderPrCostMarkdown(costSummary);

  if (options.markdownFile) {
    await writeFile(options.markdownFile, markdown, "utf-8");
    process.stderr.write(`Markdown written to ${options.markdownFile}\n`);
  }

  if (options.format === "json") {
    process.stdout.write(renderPrCostJson(costSummary));
  } else {
    process.stdout.write(markdown);
  }

  return EXIT_SUCCESS;
}

export function renderForFormat(
  format: CliOptions["format"],
  data: Parameters<typeof renderCsv>[0],
): string {
  switch (format) {
    case "csv": return renderCsv(data);
    case "json": return renderJson(data);
    case "markdown": return renderMarkdown(data);
    default: return renderTable(data);
  }
}

async function handleCommand(raw: RawOpts): Promise<number> {
  const options: CliOptions = {
    repos: raw.repo ?? [],
    org: raw.org,
    exclude: raw.exclude,
    groupBy: raw.groupBy,
    pr: raw.pr,
    since: raw.since ?? startOfMonthStr(),
    until: raw.until ?? todayStr(),
    format: raw.format,
    sort: raw.sort,
    csv: raw.csv,
    markdownFile: raw.markdownFile,
    includeForks: raw.includeForks,
    includeArchived: raw.includeArchived,
  };

  // Validate user-supplied dates (defaults are generated by our own code)
  if (raw.since) parseDate(options.since);
  if (raw.until) parseDate(options.until);
  validateDateRange(options.since, options.until);

  await checkGhCli();

  const resolved = await resolveRepos(options.org, options.repos, {
    exclude: options.exclude,
    includeForks: options.includeForks,
    includeArchived: options.includeArchived,
  });
  const resolveLog = formatResolveLog(resolved, options.org);
  if (resolveLog) process.stderr.write(resolveLog + "\n");

  const resolvedOptions: CliOptions = { ...options, repos: resolved.repos };

  if (resolvedOptions.pr !== undefined) {
    return runPrCost(resolvedOptions);
  }

  // --- Standard usage report mode ---
  const results = await fetchRuns(resolvedOptions.repos, resolvedOptions.since, resolvedOptions.until);
  const runs = results.flatMap((r) => r.runs);

  for (const r of results) {
    for (const warning of r.warnings) {
      process.stderr.write(`  Warning: ${warning}\n`);
    }
  }

  if (runs.length === 0) {
    process.stderr.write("No completed runs found in this period.\n");
    return EXIT_NO_DATA;
  }

  process.stderr.write(`\nTotal: ${runs.length} completed runs\n\n`);

  const base = aggregate(
    runs,
    resolvedOptions.repos,
    resolvedOptions.since,
    resolvedOptions.until,
    resolvedOptions.sort,
  );

  const data = resolvedOptions.groupBy === "actor"
    ? groupByActor(base, resolvedOptions.sort)
    : base;

  // Cache file export content to avoid re-rendering when stdout format matches
  let csvContent: string | undefined;
  let markdownContent: string | undefined;

  if (resolvedOptions.csv) {
    csvContent = renderCsv(data);
    await writeFile(resolvedOptions.csv, csvContent, "utf-8");
    process.stderr.write(`CSV written to ${resolvedOptions.csv}\n`);
  }

  if (resolvedOptions.markdownFile) {
    markdownContent = renderMarkdown(data);
    await writeFile(resolvedOptions.markdownFile, markdownContent, "utf-8");
    process.stderr.write(`Markdown written to ${resolvedOptions.markdownFile}\n`);
  }

  const cached = resolvedOptions.format === "csv" ? csvContent
    : resolvedOptions.format === "markdown" ? markdownContent
    : undefined;
  process.stdout.write(cached ?? renderForFormat(resolvedOptions.format, data));

  return EXIT_SUCCESS;
}

// exitOverride prevents Commander from calling process.exit directly,
// letting run() control the exit code for testability.
const program = new Command()
  .name("actions-usage")
  .description("Show GitHub Actions usage metrics per developer")
  .exitOverride()
  .version(pkg.version)
  .option("--org <org-name>", "scan all repositories in a GitHub organization")
  .option(
    "--repo <repos...>",
    "target repositories (default: detect from git remote)",
  )
  .option(
    "--exclude <repos...>",
    "exclude specific repos when scanning an org",
  )
  .option(
    "--since <date>",
    "start date YYYY-MM-DD (default: start of current month)",
  )
  .option("--until <date>", "end date YYYY-MM-DD (default: today)")
  .addOption(
    new Option("--format <type>", "output format")
      .choices(["table", "csv", "json", "markdown"])
      .default("table"),
  )
  .addOption(
    new Option("--sort <field>", "sort by")
      .choices(["minutes", "runs", "name"])
      .default("minutes"),
  )
  .addOption(
    new Option("--group-by <field>", "group results by field")
      .choices(["actor"])
  )
  .option("--pr <number>", "show CI cost for a specific pull request", (val: string) => {
    const n = Number(val);
    if (!Number.isInteger(n) || n <= 0) {
      throw new Error(`--pr must be a positive integer, got "${val}"`);
    }
    return n;
  })
  .option("--include-forks", "include forked repos when scanning an org")
  .option("--include-archived", "include archived repos when scanning an org")
  .option("--csv <path>", "export CSV to file")
  .option("--markdown-file <path>", "export markdown to file (in addition to primary format)");

export async function run(argv?: readonly string[]): Promise<number> {
  try {
    await program.parseAsync(argv as string[] | undefined);
  } catch (err) {
    if (err instanceof CommanderError) {
      // --help and --version exit with code 0
      return err.exitCode === 0 ? EXIT_SUCCESS : EXIT_ERROR;
    }
    throw err;
  }

  try {
    return await handleCommand(program.opts<RawOpts>());
  } catch (err) {
    const [msg, ...causes] = causeChain(err);
    process.stderr.write(`Error: ${msg}\n`);
    for (const cause of causes) {
      process.stderr.write(`  Caused by: ${cause}\n`);
    }
    return EXIT_ERROR;
  }
}
